# --- Ozdoby Okien (KDE Plasma) ---
hide_window_decorations no
window_padding_width    10
confirm_os_window_close 0

# --- Kolory  ---

background            #1a1a1a
foreground            #d0d0d0
cursor                #ffffff
cursor_text_color     #1a1a1a
selection_background  #333333
selection_foreground  #ffffff

# URL underline
url_color             #8ab4f8

# --- Ustawienia ramek ---
active_border_color   #444444
inactive_border_color #1a1a1a
draw_minimal_borders  yes

# --- Shader Kursora ---
cursor_shape          block
cursor_blink_interval 0
shell_integration     no-cursor

# --- Ustawienia Shadera Kursora ---
cursor_trail 2
cursor_trail_decay 0.1 0.2
cursor_trail_start_threshold 2

# --- Font ---
font_family      JetBrains Mono Nerd Font
font_size        11.0

# --- Wydajność ---
repaint_delay    8
input_delay      3
sync_to_monitor  yes
